### ISSUE TITLE
Create .env.example

### ISSUE THREAD

**Issue by adeshpande7206** [adeshpande7206/do-it-bro-hack#7]
Create an example ennvironment file

**Comment by adeshpande7206** [comment]
Keys are:
DJANGO_SECRET_KEY

**Comment by s-vamshi** [comment]
Hey, can you please assign this task to me

**Comment by Kashish-2001** [comment]
Hey can you assign this to me

**Comment by Kashish-2001** [comment]
Hey, check my PR

**Comment by s-vamshi** [comment]
@adeshpande7206 please check my PR
